# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format   
    - name: Add .NET Tools Path to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
    - name: Restore dependencies
      run: dotnet restore
    - name: Verify Code Format
      run: |
          dotnet format --verify-no-changes || (echo "Formatting issues detected. Running dotnet format to fix." && dotnet format)
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
